require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Matchflicks' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"], :hermes_enabled => true)

  target 'MatchflicksTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |bc|
        if bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '8.0'
          bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end
    end
    flipper_post_install(installer)
  end
end

target 'Matchflicks-tvOS' do
  # Pods for Matchflicks-tvOS

  target 'Matchflicks-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
